cc_library(
    name = "rocket",
    srcs = ["rocket.cpp"],
    hdrs = ["rocket.hpp"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "rocket_test",
    srcs = ["rocket_test.cpp"],
    deps = [":rocket"],
)
